plugins:
  - jekyll-feed
  - jekyll-sitemap
theme: jekyll-theme-hacker
author: Mike Levin
permalink: /:slug/
gaid: G-45KYH6XTTX
description: Welcome to the Pipulate | Pipulate.com Website!
tagline: Pipulate
welcome: Welcome to the Pipulate Website!
apex: Pipulate.com