# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sheet": "00_core.ipynb",
         "pull": "00_core.ipynb",
         "push": "00_core.ipynb",
         "poke": "00_core.ipynb",
         "pipulate": "00_core.ipynb",
         "populate": "00_core.ipynb",
         "shift_range": "00_core.ipynb",
         "check_worksheet": "00_core.ipynb",
         "cl_to_list": "00_core.ipynb",
         "cl_df_fits": "00_core.ipynb",
         "a1": "00_core.ipynb",
         "google_service": "00_core.ipynb",
         "api_date": "00_core.ipynb",
         "human_date": "00_core.ipynb",
         "email": "00_core.ipynb",
         "Unbuffered": "00_core.ipynb",
         "gspread_sheet": "00_core.ipynb",
         "column_uniqueness": "00_core.ipynb",
         "gui": "00_core.ipynb",
         "link": "00_core.ipynb",
         "key": "00_core.ipynb",
         "credentials": "00_core.ipynb",
         "gspread_authorized": "00_core.ipynb",
         "stdout": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://miklevin.github.io/pipulate/"

git_url = "https://github.com/miklevin/pipulate/tree/main/"

def custom_doc_links(name): return None
